= Уровень подготовки пользователя

== Пользователи модуля {wc}

{wc} является основным рабочим местом пользователя {dv}.

.Пользователи модуля {wc} должны:
* Обладать навыками работы с xref:requirements-software.adoc#browser[веб-браузерами].
* Свободно осуществлять базовые действия в операционной системе клиентского устройства.
* Обладать знаниями предметной области.
* Обладать навыками работы с модулем _{wincl}_, а также с другими модулями и приложениями, которые установлены в системе {dv} (желательно).
* Пройти обучение по работе с модулем {wc}.

== Администраторы модуля {wc}

Администратор модуля xref:admin:install.adoc[устанавливает {wc}] и выполняет xref:admin:initial-configuration.adoc[первоначальную настройку],

.Администратор {wc}а должен:
* Обладать навыками администрирования операционных систем:
** Microsoft Windows Server {serv-4}.
** Microsoft Windows Server {serv-3}.
** Microsoft Windows Server {serv-2}.
** Microsoft Windows Server {serv-1}.
* Иметь опыт настройки {iis}, а также обладать достаточным знанием IIS для включения требуемых компонентов.
* Должен уметь установить и настроить необходимое ПО, указанное в разделе xref:requirements-signature.adoc[].
* Быть способным распространить на клиентские рабочие места настройки адреса и порта, используемые модулем {wc}.
* Обладать навыками администрирования других модулей и приложений, установленных в системе {dv}.

== Пользователь программы {kvr} (инженер)

Основной обязанностью пользователя программы {kvr} (инженера) является создание и настройка решений и разметок.

.Пользователи программы должны:
- Иметь опыт работы с персональным компьютером на базе операционной системы Windows на уровне квалифицированного пользователя.
- Свободно осуществлять базовые операции в ОС Windows.

После настройки и распространения решения его поддержка выполняется инженером {dv} без привлечения разработчиков.

== Разработчики расширений для {wc}

{kvr} позволяет объединять настройки разметок, условия выбора и данные локализации в решение, которое может быть выгружено для последующего распространения. При необходимости изменения стандартных решений для системы могут быть разработаны собственные решения на базе {wc}а (опционально).

.Для разработки решений необходимо:
* Обладать опытом разработки на языках TypeScript и C#, создания CSS стилей.
* Обладать навыками разработки веб-приложений с использованием библиотеки https://reactjs.org/[React].
* Иметь опыт разработки Решений на платформе {dv} (желательно).
* Ознакомиться с разделами "xref:TSK-11773@programmer:WebClient:development.adoc[Руководство по разработке решений]" и "xref:TSK-11773@programmer:ROOT:development.adoc[Руководство разработчика {dv}]".
