= Особенности настройки кластера {wc}

С целью повышения отказоустойчивости и распределения нагрузки, администратор может объединить несколько экземпляров модуля {wc} в кластер.

[#conditions]
== Обязательные условия для работы кластера

* Каждый экземпляр {wc}а должен иметь уникальный адрес подключения.
* Балансировщик нагрузки должен передавать заголовок X-Forwarded-Proto.

[#preparation]
=== Подготовка узлов кластера

.Чтобы подготовить узлы кластера {wc}а к работе:
// . xref:install-server.adoc#windows[Установите] серверное расширение {wc} на машине с Windows.
. xref:install-server.adoc#linux[Установите и настройте] модуль {wc} на первом компьютере кластера.
. xref:install-server.adoc#linux[Установите и настройте] модуль {wc} на последующих узлах кластера.
. Настройте балансировщик нагрузки, например, Nginx.
+
.Конфигурационный файл `/etc/nginx/sites-available/default`:
+
[source,json]
----
    upstream app {
        ip_hash; <.>
        server 172.16.18.182:5004; <.>
        server 172.16.18.240:5004;
    }

    server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        ssl_certificate /home/user/172.16.18.182.crt;
        ssl_certificate_key /home/user/172.16.18.182.key;
        server_name _;

        location / {
            proxy_pass https://app/;
        }
    }
----
<.> Параметр, перенаправляющий все запросы от одного IP-адреса на один сервер. Обязательный парамер, в противном случае не авторизация не будет работать.
<.> IP-адреса узлов кластера.

[#create-cert]
=== Сгенерируйте отпечаток

// tag::webconfig[]
. Если {wc} использует HTTPS, создайте сертификат с помощью OpenSSL. Пример использования утилиты приведён в разделе администрирования модуля {mc}: "xref:engineer:ROOT:create-cert.adoc[]".
. Установите и настройте {wc} на втором компьютере кластера (далее -- *УЗЕЛ 2*).
+
WARNING: Экземпляр {wc}а, установленный на втором и последующих узлах кластера, должен быть настроен на работу с теми же сервером и базой данных {dv}, что и УЗЕЛ 1.
+
// tag::webconfig[]
. В конфигурационном файле `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows на УЗЛЕ 1 укажите путь к полученному сертификату в элементе `"Https":` (`"Http":`, если используется незащищённое соединение). Фрагмент конфигурационного файла приведён ниже:
+
[source,json]
----
{
"Https": {
  "Url": "https://*:5005",
  "Certificate": {
    "Path": "/home/user/certificate.pfx", <.>
    "Password": "password", <.>
    "KeyPath": "KeyPath" <.>
    }
  }
}
----
<.> Путь к сертификату
<.> Пароль от сертификата
<.> Путь к ключу сертификата
// end::webconfig[]
+
include::partial$excerpts.adoc[tags=ifabsent]
+
. Сгенерируйте сертификат на втором узле.
. Откройте конфигурационный файл `{webconfig-lin}` в Linux и `{webconfig-cp}` в Windows на УЗЛЕ 2 и укажите путь к полученному сертификату.
. Повторите шаги инструкции для третьего и последующих узлов кластера {wc}а.
// . Если планируется работа через протокол HTTP, в конфигурационном файле балансировщика нужно убрать параметр `secure`. Если ничего не прописать, по умолчанию параметр `secure` = `true`. В зависимости от значения параметра будет использоваться пот `80` (для HTTP) или порт `443` (HTTPS).
// end::webconfig[]

[#nginx]
== Настройка nginx

При использовании прокси-сервиса nginx, установленного на отдельной машине от {wc}а необходимо в корень конфигурационного файла {wc} добавить настройку `ForwardedHeaders/KnownProxies`, разрешающую принимать от прокси-сервиса заголовки. Если {wc} и прокси установлены на одном ПК, ничего добавлять не нужно.

[source,json]
----
{
  "ForwardedHeaders":
  {
    "KnownProxies": {
      "proxy1": "{123.456.789}" <.>
    }
  }
}
----
<.> Укажите IP-адрес сервера nginx. Вместо `proxy1` можно использовать любое уникальное название. В значении параметра указывается только IP-адрес. При необходимости можно указывать несколько прокси-сервисов.

На стороне прокси-сервиса должна быть настроена передача заголовков: `X-Forwarded-Proto`, `X-Forwarded-Host`, `X-Forwarded-Port` (если порт не соответствует схеме), `X-Forwarded-For`.

.Пример для nginx:
[source]
----
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Port $server_port;
----

Если за прокси-сервисом скрыто несколько экземпляров {wc}а, нужно установить настройку `Docsvision/WebClient/SettingGroups/WebClient/ServerR7JwtAccessToWebClientEnable` в значение `true`. Если настройка отсутствует, добавьте её самостоятельно.

.Пример конфигурации:
[source,json]
----
{
  "Docsvision": {
    "WebClient": {
      "SettingGroups": {
        "WebClient": {
          "ServerR7JwtAccessToWebClientEnable": true
        }
      }
    }
  }
}
----

См. также *xref:dvweb-cluster.adoc[Настройка утилиты DVWebTool для работы в кластере]*.
