= Подписание без скачивания файла

По умолчанию подписываемый файл не скачивается в браузер для последующего использования, вместо этого скачивается только хэш подписываемого файла.

Поведение по умолчанию требует наличия КриптоПро .NET с соответствующей лицензией на сервере {wc}а. ПО ускоряет формирование подписи, особенно при подписании файлов большого размера. При необходимости администратор может отключить оптимизацию при помощи параметра `CalculateSignatureHashOnServer` в конфигурационном файле {wc}а.

// tag::webconfig[]
.Чтобы изменить режим скачивания подписи:
. Убедитесь, что xref:ROOT:requirements-signature.adoc#bes[на сервере {wc}а установлено ПО] КриптоПро .NET с соответствующей лицензией.
. Откройте конфигурационный файл, расположенный по адресу `{webconfig-win}`.
. Перейдите к разделу {setgroups-wc}.
. Измените значение параметра `CalculateSignatureHashOnServer` с `true` на `false`.
+
[source,xml]
----
<Setting Name="CalculateSignatureHashOnServer" Value="True" /> <.>
----
<.> `true` -- скачивается только хэш подписываемого файла (значение по умолчанию), `false` -- будет скачиваться полностью подписываемый файл (устаревшее поведение).
+
[NOTE]
====
* Если алгоритм подписания не поддерживается,
// или не установлены xref:ROOT:requirements-signature.adoc[необходимые компоненты КриптоПро],
действует стандартная логика подписания со скачиванием файла в браузер.

* В данный момент подписание без скачивания файла не действует с облачной подписью.
====
// end::webconfig[]
