= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

// tag::webconfig[]
Базовые настройки журналирования представлены в панели управления (xref:control-panel-webc.adoc[Раздел "WebClient"]). Расширенные настройки осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig-win}`.
. Перейдите к секции menu:configuration[nlog].
. Измените параметры журналирования.
+
Измените значение атрибута *_fileName_* элемента menu:targets[target > target], чтобы настроить путь для сохранения журнала работы.
+
NOTE: В *_fileName_* можно использовать допустимые для Nlog переменные (https://github.com/nlog/NLog/wiki/File-target), например: `C:\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
Измените значение атрибута *_level_* элемента menu:rules[logger], например, на *_trace_*, чтобы включить протоколирование всех типов событий.
+
NOTE: Допустимые уровни протоколирования приведены на странице https://github.com/nlog/NLog/wiki/Configuration-file#log-levels.
+
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/api/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе *{dv-admins-serv}*. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*). Передать уровень журналирования можно, например, при помощи GET-параметра `minLevel`:

 api/Log/SetLogLevel?minLevel=0

// Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а.
После рестарта IIS уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====

[#advanced-logging]
== Расширенное журналирование

{wc} поддерживает расширенное журналирование параметров производительности. Сюда входит точное логирование времени выполнения запросов {wc}а, время выполнения запросов к *{sss-new}* с привязкой к запросу {wc}а.

Для настройки доступно три фильтра журнала: По пользователю, По конкретному адресу, По времени запроса.

После включения диагностического логирования можно делать запросы. Если в параметре будет слеш (`\` или `/`), его необходимо переводить в URL код. Иными словами, заменять `example\usr01` на `example%5Cusr01`.

.Для отдельного запроса {wc}а можно посмотреть:
* Какие запросы к *{sss-new}* выполнялись.
* Время, потраченное на выполнение каждого из них.
* Время, проведённое запросами на стороне *{sss-new}* и на стороне {wc}а.
* Параметры запросов.

.Эта информация позволяет:
* Устанавливать причины аномально быстрого или медленного выполнения запроса {wc}а.
* Выявлять ошибки и неоптимальные места в работе {wc}а и Object Manager.
* Обнаруживать блокировки {wc}а и Object Manager.
* Выявлять проблемные запросы на сервере.

Чтобы включить диагностическое логирование, нужно в конфигурационном файле {wc}а для параметра `EnableDiagnosticsLogger` в разделе {setgroups-sys} указать значение `1`:

[source,json]
----
 <Docsvision>
    <WebClient>
      <SettingGroups>
        <SettingGroup Name="System">
          <Setting Name="EnableDiagnosticsLogger" Value="1" /> <.>
        </SettingGroup>
      </SettingGroups>
    </WebClient>
  </Docsvision>
----
<.> Включить расширенное журналирование.
