= Настройка журналирования

События {wc}а протоколируются с помощью компонента NLog (http://nlog-project.org).

include::partial$nlog.adoc[]

// tag::webconfig[]
Базовые настройки журналирования представлены в панели управления (xref:control-panel-webc.adoc[Раздел "WebClient"]). Расширенные настройки осуществляются в конфигурационном файле {wc}а.

. Откройте конфигурационный файл `{webconfig}`.
. Перейдите к секции menu:configuration[nlog].
. Измените параметры журналирования.
+
Измените значение атрибута *_fileName_* элемента menu:targets[target > target], чтобы настроить путь для сохранения журнала работы.
+
NOTE: В *_fileName_* можно использовать допустимые для Nlog переменные (https://github.com/nlog/NLog/wiki/File-target), например: `C:\Logs\$\{level}\WebClient_$\{shortdate}.log`.
+
Измените значение атрибута *_level_* элемента menu:rules[logger], например, на *_trace_*, чтобы включить протоколирование всех типов событий.
+
NOTE: Допустимые уровни протоколирования приведены на странице https://github.com/nlog/NLog/wiki/Configuration-file#log-levels.
+
Для получения дополнительной информации о других настройках NLog обратитесь к документации по данной платформе.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла.
+
[NOTE]
====
Уровень журналирования может быть изменён методом `/api/Log/SetLogLevel`, если пользователь, который вызывает метод, состоит в группе *{dv-admins-serv}*. Методом можно задать следующие уровни: *_Trace = 0_*, *_Debug = 1_*, *_Info = 2_*, *_Warn = 3_*, *_Error = 4_* (любое другое значение будет распознано как *_Error_*).

Данный способ применим для случая, когда есть потребность не перезагружать пул {wc}а. После рестарта IIS уровень журналирования будет возвращён в исходное состояние в соответствии с конфигурационным файлом.
====

[#advanced-logging]
== Расширенное журналирование

{wc} поддерживает расширенное журналирование параметров производительности. Сюда входит точное логирование времени выполнения запросов {wc}а, время выполнения запросов к {sss} с привязкой к запросу {wc}а.

.Для отдельного запроса {wc}а можно посмотреть:
* Какие запросы к {sss} выполнялись.
* Время, потраченное на выполнение каждого из них.
* Время, проведённое запросами на стороне {sss}, а сколько на стороне {wc}а.
* Параметры запросов.

.Эта информация позволяет:
* Устанавливать причины аномально быстрого или медленного выполнения запроса {wc}а.
* Выявлять ошибки и неоптимальные места в работе {wc}а и Object Manager.
* Обнаруживать блокировки {wc}а и Object Manager.
* Выявлять проблемные запросы на сервере.

Журналирование ведётся в формате `.csv` и в дальнейшем может быть проанализирован через офисное приложение для работы с таблицами, например {ms} Excel. Расширенный журнал по умолчанию сохраняется в стандартный журнал лог {wc}а, но при помощи параметров конфигурации NLog можно настроить запись в отдельный файл.

Ведение расширенного журнала включается и отключается для определенного пользователя. Чтобы включить ведение расширенного журнала для пользователя, нужно выполнить запрос в браузере:

 http://wserver/webc16/api/DiagnosticsLog/AddLogUser?user=server%5Cusername

Чтобы отключить ведение расширенного журнала, нужно выполнить запрос в браузере:

  http://wserver/webc16/api/DiagnosticsLog/Reset

[source,xml]
----
  <nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" autoReload="true" throwExceptions="false" internalLogLevel="Off" internalLogFile="nlog-internal.log">
    <targets>
      <target name="DefaultLogFileAsync" xsi:type="AsyncWrapper">
        <target name="DefaultLogFile" xsi:type="File" encoding="UTF-8" fileName="C:\Dev\Logs\WebC16.log" layout="[${longdate}][${level}][${callsite}] ${message} ${exception:format=tostring,Data}" />
      </target>
      <target name="UnreadCountersLogFileAsync" xsi:type="AsyncWrapper">
        <target name="UnreadCountersLogFile" xsi:type="File" encoding="UTF-8" fileName="C:\Dev\Logs\WebC16_UnreadCounters.log" layout="[${longdate}][${level}][${callsite}] ${message} ${exception:format=tostring,Data}" />
      </target>
	  <target name="DiagnosticsLog" xsi:type="AsyncWrapper">
        <target name="DiagnosticsLogFile" xsi:type="File" encoding="UTF-8" fileName="C:\Dev\Logs\WebC16Diagnostics PID${processId}.log" layout="${message}" /> <.>
      </target>
	  <target name="DiagnosticsLogSS" xsi:type="AsyncWrapper">
        <target name="DiagnosticsLogSSFile" xsi:type="File" encoding="UTF-8" fileName="C:\Dev\Logs\WebC16DiagnosticsSS PID${processId}.log" layout="${message}" /> <.>
      </target>
    </targets>
    <rules>
        <logger name="*" minlevel="Debug" writeTo="DefaultLogFileAsync">
            <filters>
                <when condition="contains('${message}','System.Security.Cryptography.CryptographicException: ID1014')" action="ignore" />
                <when condition="contains('${message}','TSV_DV')" action="ignore" />
				<when condition="contains('${message}','TSV_SS')" action="ignore" />
            </filters>
        </logger>
        <logger name="*" minlevel="Debug" writeTo="DiagnosticsLog">
            <filters>
                <when condition="not contains('${message}','TSV_DV')" action="ignore" /> <.>
            </filters>
        </logger>
		<logger name="*" minlevel="Debug" writeTo="DiagnosticsLogSS">
            <filters>
                <when condition="not contains('${message}','TSV_SS')" action="ignore" /> <.>
            </filters>
        </logger>
    </rules>
  </nlog>
----
<.> Адрес хранения журнала {wc}а. В параметре `target` важно добавить в имя файла `$\{processId}`/. Например `WebCDiagnostics PID$\{processId}.log` и указать `layout="$\{message}"`.
<.> Адрес хранения журнала {sss}. В параметре `target` важно добавить в имя файла `$\{processId}`/. Например `WebCDiagnostics PID$\{processId}.log` и указать `layout="$\{message}"`.
<.> Минимальный уровень журналирования ошибок {wc}а.
<.> Минимальный уровень журналирования ошибок {sss}.