= Повторное создание сессий при длительных запросах

При обнаружении запроса, продолжающегося более, чем заданное количество секунд (по умолчанию `30` секунд), например длительного запроса полнотекстового поиска, поверх основного интерфейса появляется всплывающая панель, которая позволяет повторно создать пользовательскую сессию.

Панель содержит сообщение `Запросы на сервере выполняются дольше обычного. Пересоздать сеанс и открыть новую вкладку?` и кнопку *ОК*. При нажатии на кнопку панель будет скрыта, будет создана новая пользовательская сессия, а также открыта главная страница {wc}а. Обработка длительного запроса будет продолжена в фоновом режиме.

Для каждого пользователя может быть задан лимит на повторное создание сессий при длительных запросах. По умолчанию лимит составляет `3` повторных создания, администратор может изменить вплоть до `0`. что будет означать отсутствие ограничения.

Если количество созданных повторно сессий достигло лимита, новая сессия не создается, пользователю будет выдано предупреждение с текстом: `Продолжение работы в новой вкладке временно недоступно. Пожалуйста, дождитесь завершения текущих запросов`.

Если при выполнении длительного запроса пользователь закрыл вкладку или окно браузера, запрос автоматически переходит в фоновый режим, а сессия будет создана повторно без дополнительного подтверждения.

// tag::webconfig[]
.Чтобы настроить длительность запроса, после которого будет предложено создать новую сессию:
. Откройте конфигурационный файл `{webconfig-win}`.
. Перейдите к группе настроек {setgroups-wc}.
. Найдите настройку `SessionRecreationDelaySec`.
. Укажите новое ограничение в параметре `Value`. Значение по умолчанию `30`, минимальное значение -- `10`.
+
[source]
----
<SettingGroup Name="WebClient">
  <Setting Name="SessionRecreationDelaySec" Value="30" /> <.>
</SettingGroup>
----
<.> `SessionRecreationDelaySec` -- длительность запроса в секундах по истечении которой появляется всплывающая панель с вопросом повторно создать сессию.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла и перезапустите IIS.

// tag::webconfig[]
.Чтобы настроить лимит создаваемых повторно сессий:
. Откройте конфигурационный файл `{webconfig-win}`.
. Перейдите к группе настроек {setgroups-wc}.
. Найдите настройку `SessionRecreationMax`.
. Укажите новое ограничение в параметре `Value`. Значение по умолчанию `3`, минимальное значение -- `0` (ограничения отсутствуют).
+
[source]
----
<SettingGroup Name="WebClient">
  <Setting Name="SessionRecreationMax" Value="3" /> <.>
</SettingGroup>
----
<.> `SessionRecreationMax` -- максимальное число повторно созданных сессий при длительных запросах.
// end::webconfig[]
+
. Сохраните изменения конфигурационного файла и перезапустите IIS.

[#logging]
== Журналирование

События, связанные с повторным созданием сессий, фиксируются в журнале {wc}а при уровне логирования `Warn` (уровень по умолчанию -- `Error`).

.При успешном повторном создании сессии в журнал записывается следующая информация:
* Идентификатор сессии
* Идентификатор пользователя
* Идентификатор запроса
* Тип запроса
* Время запуска запроса
* Время пересоздания сессии

.При исчерпанном лимите на пересоздание сессии в журнал записывается следующая информация:
* Идентификатор сессии
* Идентификатор пользователя
* Факт попытки создания новой сессии

.При закрытии текущей сессии в журнал записывается следующая информация:
* Идентификатор сессии
* Идентификатор пользователя
